name: "My Action"
description: "My custom action"
author: "Angel Roman"

run:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Versión principal recomendada

    - name: Saludo
      id: Saludo
      shell: bash
      run: |
        echo "Hello World"
        echo "Hello ${{ inputs.my_input }}"
        echo "Hello ${{ inputs.my_input2 }}"

branding:
  icon: "terminal"
  color: "blue"

inputs:
  my_input:
    description: "My primer mennsaje"
    required: true
    default: "Angel Roman"
  my_input2:
    description: "My segundo mennsaje
    required: false
    default: "Grandes Líderes"


