name: "My Action"
description: "My custom action"
author: "Angel Roman"

inputs:
  my_input:
    description: "My primer mensaje"
    required: true
    default: "Angel Roman"
  my_input2:
    description: "My segundo mensaje"  # Comillas cerradas
    required: false
    default: "Grandes Líderes"

runs:
  using: "composite"
  steps:
    - name: Saludo
      shell: bash
      run: |
        echo "Hello World"
        echo "Hello ${{ inputs.my_input }}"
        echo "Hello ${{ inputs.my_input2 }}"

branding:
  icon: "terminal"
  color: "blue"