name: "My Action"
description: "My custom action"
author: "Angel Roman"

run:
  using: "composite"
  steps:
    - name: Step 1
      id: step_id
      shell: bash
      run: |
        echo "Hello World"

branding:
  icon: "terminal"
  color: "blue"

inputs:
  my_input:
    description: "My input"
    required: true
    default: "Hello World"
  my_input2:
    description: "My second input"
    required: false
    default: "Hello World 2"


