name: Despliegue por SSH

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Selecciona el servidor de despliegue'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      branch:
        description: 'Selecciona la rama a desplegar'
        required: true
        default: 'master'
        type: choice
        options:
          - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configurar conexión SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PASSWORDPHPMYADMIN }}

      - name: Ejemplo de comando SSH (listar directorio remoto)
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'ls -l /var/www/'

      - name: Fin de la conexión SSH
        run: echo "Conexión SSH configurada y probada."
