name: Hola Mundo Workflow

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Aroman1984
          MYSQL_DATABASE: inventory_db
        ports:
          - 3306:3306
        # Añadir opciones para evitar advertencias
        options: >-
          --health-cmd "mysqladmin ping -pAroman1984"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Si aún necesitas submódulos

      - name: Esperar inicio de MySQL
        run: sleep 20  # Espera inicial para que MySQL se inicie

      - name: Verificar conexión a MySQL
        run: |
          mysql -h 127.0.0.1 -u root -pAroman1984 -e "SHOW DATABASES;"

      - name: Ejecutar comandos básicos
        run: |
          echo "Hola Mundo"
          touch hola.txt
          echo "Hola Mundo" >> hola.txt
          cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ejecutar script Linux
        run: |
          ls -la
          apt-get update  # Eliminar "sudo"
          ./.github/script.sh

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Usar versión LTS

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mysqli, pdo_mysql  # Solo extensiones esenciales
          tools: composer:v2.6