name: Hola Mundo

on: [push]

jobs:
  hola:
    - name: Hola Mundo
      run: echo "Hola Mundo"

  steps:
    - name: Crear archivo
      run: touch hola.txt
    
    - name: Escribir mensaje
      run: echo "Hola Mundo" >> hola.txt
      
    - name: Mostrar contenido
      run: cat hola.txt

  other_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: LS
        run: ls

