name: Hola Mundo Workflow

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: personas_db
          MYSQL_ROOT_PASSWORD: Aroman1984
          MYSQL_ALLOW_EMPTY_PASSWORD: "false"
        options: >-
          --health-cmd "mysqladmin ping -pAroman1984"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Ejecutar comandos básicos
        run: |
          echo "Hola Mundo"
          touch hola.txt
          echo "Hola Mundo" >> hola.txt
          cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Esperar inicio de MySQL
        run: |
          for i in {1..10}; do
            mysqladmin ping -h127.0.0.1 -uroot -pAroman1984 --silent && break
            sleep 5
          done

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client python3 python3-pip
          pip3 install mysql-connector-python

      - name: Verificar entorno
        run: |
          ls -la
          mysql -h 127.0.0.1 -u root -pAroman1984 -e "SHOW DATABASES;"

      - name: Ejecutar script Python
        run: python3 script.py

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Mostrar versión Node
        run: node --version

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip, gd, mysqli, pdo_mysql, bcmath, soap, intl, redis
          coverage: none
          tools: composer:v2.1.3

      - name: Ejecutar script Shell
        run: |
          chmod +x ./.github/script.sh
          ./.github/script.sh