name: Hola Mundo Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      mensaje_personalizado:
        description: 'Mensaje para imprimir'
        required: false
        default: '¡Hola desde la ejecución manual!'
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'
  

jobs:
  saludo_personalizado:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ejecutar mi acción
        id: mi_accion
        uses: ./.github/actions/my_action
        with:
          my_input: "¡Saludos desde el workflow!"
          my_input2: "Es un placer."

      - name: Mostrar salidas de la acción
        run: |
          echo "El saludo completo generado por la acción es: ${{ steps.mi_accion.outputs.saludo_completo }}"
          echo "El primer mensaje de la acción fue: ${{ steps.mi_accion.outputs.primer_mensaje }}"

  hola:
    runs-on: ubuntu-latest
    needs: saludo_personalizado
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ejecutar comandos básicos
        run: |
          echo "Hola Mundo"
          touch hola.txt
          echo "Hola Mundo" >> hola.txt
          cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: LS
        run: ls -la

      - name: Ejecutar script Linux
        run: |
          ls -la
          sudo apt-get update
          chmod +x ./.github/script.sh
          ./.github/script.sh
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: latest

      - name: node version
        run: node --version

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, curl, zip, gd, mysqli, pdo_mysql, bcmath, soap, intl, redis
          coverage: none
          tools: composer:v2.1.3
  otro_job_paralelo:
    runs-on: windows-latest
    steps:
      - name: Saludo en Windows
        run: echo "Hola desde Windows"
  job_final:
    needs: other
    runs-on: ubuntu-latest
    steps:
      - name: Job finalizado
      run: echo "Todos los jobs anteriores se completaron"