name: Hola Mundo Workflow

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Versión principal recomendada
        
      - name: Ejecutar comandos básicos
        run: |
          echo "Hola Mundo"
          touch hola.txt
          echo "Hola Mundo" >> hola.txt
          cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Ejecutar script Linux
        run: |
          ls -la
          sudo apt-get update  # Comando correcto para Linux
          chmod +x ./.github/script.sh
          ./.github/script.sh