name: Hola Mundo

on: [push]

jobs:
  hola:
    steps:
    -name: Hola Mundo
      run: echo "Hola Mundo"

    -name: Crear archivo
      run: touch hola.txt
    
    -name: Escribir mensaje
      run: echo "Hola Mundo" >> hola.txt
      
    -name: Mostrar contenido
      run: cat hola.txt

  other:
    runs-on: ubuntu-latest
    
    steps:
    -name: LS
      run: ls