name: Hola Mundo Workflow

on: [push]

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Versión principal recomendada

      - services:
        mysql:
          image: mysql:5.7
          ports:
            - 3306:3306
          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: inventory_db
            MYSQL_USER: root
            MYSQL_PASSWORD: Aroman1984
          options: >-
            --health-cmd "mysqladmin ping --silent" --health-interval 10s
            --health-timeout 5s --health-retries 3
        
      - name: Ejecutar comandos básicos
        run: |
          echo "Hola Mundo"
          touch hola.txt
          echo "Hola Mundo" >> hola.txt
          cat hola.txt

  other:
    runs-on: ubuntu-latest
    needs: hola
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: LS
        run: ls -la

      - name: Ejecutar script Linux
        run: |
          ls -la
          sudo apt-get update  # Comando correcto para Linux
          chmod +x ./.github/script.sh
          ./.github/script.sh

      - name: Ejecutar script Actions
        run: |
          echo "Hola Mundo desde el script de Actions"
          chmod +x ./.github/actions/my_action/action.yml


      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: latest  # Cambia esto a la versión de Node.js que necesites

      - name: node version
        run: node --version

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Cambia esto a la versión de PHP que necesites
          extensions: mbstring, xml, curl, zip, gd, mysqli, pdo_mysql, bcmath, soap, intl, redis
          coverage: none  # Cambia esto a 'xdebug' si necesitas cobertura de código
          tools: composer:v2.1.3  # Cambia esto a la versión de Composer que necesites

#git rm --cached Modulo4/CursoVSCodeGitHubCopilot/Calculadora/matematicas   para eliminar el seguimineto y no darm  fallo de git
